print(10 == 10)
print(10 == True)
print(10 == 'durga')
print(True == 0)
print(True == 1)
print(True == False)

print(10 != 10)
print(10 != 20)
print(10 != 'durga')
print('durga' == 'Durga')
print('durga' == 'durga')
