# Logical 'and'
print(f'10 and 3 is {10 and 3}')
print(f'10 and 0 is {10 and 0}')
print(f'0 and 20 is {0 and 20}')
print(f'10.22 and 20.2 is {10.22 and 20.2}')
print(f'string1 and 0 is {"string1" and 0}')
print(f'True and False is {True and False}')
print(f'False and True is {False and True}')
print(f'False and False is {False and False}')
print(f'True and True is {True and True}')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
# Logical 'or'
print(f'10 or 5 is {10 or 5}')
print(f'0.222 or 10 is {0.222 or 10}')
print(f'0 or 10 is {0 or 10}')
print(f'"string1" or 0 is {"string1" or 0}')
print(f'0 or "string1" is {0 or "string1"}')
print(f'0 or 1 is {0 or 1}')
print(f'1 or 0 is {1 or 0}')
print(f'0 or 0 is {0 or 0}')
print(f'1 or 1 is {1 or 1}')
print(f'True or False is {True or False}')
print(f'False or False is {False or False}')
print(f'False or True is {False or True}')
print(f'True or True is {True or True}')
print('##############################################')
# Logical 'not'
print(f'not 10 is {not 10}')
print(f'not 0 is {not 0}')
print(f'not 1 is {not 1}')
print(f'not "string" is {not "string"}')
print(f'not False is {not False}')
print(f'not True is {not True}')
